### ISSUE TITLE
iot-lora-configure website needs to have correct router settings

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/IoTLoRaRange#1]
The website configuration does not set the correct TTN Router address as to what has been selected in the drop down box.

Along with this it should be updated to say the estimated altitude is in meters.

**Comment by ryanteck** [comment]
Should now be fixed and deployed to temp instance.

Thanks to @cleoqc for reporting this issue.

**Comment by shawaj** [comment]
Want to push this to the server or still more testing to do?

**Comment by ryanteck** [comment]
I think if we leave it for a day or two. I'll go through and test each
server tomorrow.

**Comment by shawaj** [comment]
Awesome
