### ISSUE TITLE
MicroBit LoRa Node: add support 'at+rd_adc' command to MakeCode lib

### ISSUE THREAD

**Issue by BombilCalabasov** [PiSupply/IoTLoRaRange#10]
The big connector U$3 with 8 GPIOs is presented on the node's PCB but we cannot use it in MakeCode applications.  Especially, read analog level from pin.

**Comment by ryanteck** [comment]
Closed to be moved to https://github.com/PiSupply/pxt-iot-lora-node/issues/38

It'll still be implemented just moving to correct repo.
