### ISSUE TITLE
Orange PC +

### ISSUE THREAD

**Issue by coraxyn** [PiSupply/IoTLoRaRange#12]
Using Orange PC Plus, Armbian and LoRa pHat.  Connecting via UART3 and /dev/ttyS3

Connecting and configuring UART seems to work, writing to UART may be working, but cannot get anything back from LoRa (via UART)
Any recommendations?

**Comment by ryanteck** [comment]
Hi @coraxyn ,

so to confirm that you're able to confirm you've configured UART correctly under Armbian and can confirm that it's working but it's just the LoRa pHAT not working? 

Have you toggled IO on the GPIO pin used for reset? This would be Pin 11 or PA1

To reset you would pull the pin low then high

**Comment by coraxyn** [comment]
Will try this.  Thank you

**Comment by ryanteck** [comment]
The baudrate should also be 115200 as default.

**Comment by coraxyn** [comment]
Tried as you suggested, but nothing.

Looking at various python, c, and pascal code - all read or write to
something near /sys/class/gpio .. something.  Looking at file system the
specified file(s) in gpio directory do not exist.   Am running
armbian/buster.   Can you help?  Am totally lost

Paul

**Comment by coraxyn** [comment]
After further reading found proper 'files' to use.  Thank you

**Comment by ryanteck** [comment]
Hi Paul, I assume this means it's all working now and I can close this issue?

**Comment by coraxyn** [comment]
Yep
