### ISSUE TITLE
Issue running ./mp_pkt_fwd RPI 4 8GB

### ISSUE THREAD

**Issue by wkirby007** [PiSupply/IoTLoRaRange#18]
Hi, I've been through your advanced compiler instructions and getting the following error trying to run the packet forwarder.

./mp_pkt_fwd: error while loading shared libraries: libttn-gateway-connector.so: cannot open shared object file: No such file or directory

**Comment by ryanteck** [comment]
It sounds like you missed the step when compiing the ttn-gateway-connector to then copy it by running ```sudo cp bin/libttn-gateway-connector.so /usr/lib

```

**Comment by wkirby007** [comment]
Perfect, thanks for the help.

**Comment by ryanteck** [comment]
No problem, if you have any other issues feel free to re-open this ticket.
