### ISSUE TITLE
Gateway EUI?

### ISSUE THREAD

**Issue by jfnunez-dev** [PiSupply/IoTLoRaRange#24]
if a need to register the gateway with gateway eui parameter in TTN , how i need to do it? i am only see register by gateway ID in the tutorial, it is necessary to modify the local_conf.json file with adding or modify the parameter ?

**Comment by ryanteck** [comment]
Hi @jfnunez-dev ,

From what I remember you're using the compilie it yourself method, and yes it is possible to configure it in "legacy" mode.

To do this you'd need to do the following:

Change serv_type to "semtech"

Remove the lines "serv_gw_id" and "serv_gw_key".

Create your own EUI and change the line "gateway_ID" to the EUI you create and then set this up on the LoRa provider.

Typically we suggest using the mac address of the gateway, so if my mac address is "7c:dd:90:4f:fa:61" you'd first remove the :s making it "7cdd904ffa61" and then in the middle (6 characters in) adding FFFF resulting in my EUI being "7CDD90FFFF4FFA61".

**Comment by jfnunez-dev** [comment]
how i get the mac address of the gateway from this product?

**Comment by ryanteck** [comment]
Sorry, I misworded. By gateway I meant the host you're using (So the Tinkerboard) and using the mac address of the ethernet controller. (Typically found by using ifconfig).

**Comment by ryanteck** [comment]
Hi @jfnunez-dev ,

Did this resolve your issue?

**Comment by jfnunez-dev** [comment]
hi, i dont make any test yet with EUI, i am verifying with TTI for futures gateways hats

Best regards
