### ISSUE TITLE
network traffic? with tcpdump?

### ISSUE THREAD

**Issue by jfnunez-dev** [PiSupply/IoTLoRaRange#27]
its possible to listen the data with tcpdump with this hat?, i ask because a did it with another rak module (Rak 2245), i need to verify the data coming from node to the gateway, i dont know if its possible with this packet forwarder 
Thanks in advance

**Comment by ryanteck** [comment]
Hi @jfnunez-dev ,

This isn't something I've tried myself as have had no need to, you would use the command I gave you to view the logs to see if it's receiving the data.

As also previously mentioned the setup you're using isn't fully supported so we can't help with every question sorry witht this being the first one.
