### ISSUE TITLE
40 pins IoT LoRa Gateway HAT description

### ISSUE THREAD

**Issue by jfnunez-dev** [PiSupply/IoTLoRaRange#28]
Hi,
Is there any document with the description of the 40 pin connector with the pin uses?
i uses the physical pin 13 (tx)-14 (Gnd)-15 (rx) for serial connection to my mac but after the compilation of all the setup this pins dont work anymore for serial connection.
is any script or service who take this pins for uses? i know the rak833 uses SPI connection and shouldnt take this pins.

Please help
Regards

**Comment by ryanteck** [comment]
There's a pinout at https://github.com/PiSupply/IoTLoRaRange/tree/master/IoT%20Lora%20Gateway%20HAT and https://pinout.xyz/pinout/iot_lora_gateway_hat

UART is used to communicate to an optional GPS module which is why those pins might get used.
