### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by ChristopherRush** [PiSupply/IoTLoRaRange#4]
Add images here to link in repo

**Comment by ChristopherRush** [comment]
![IoT-LoRa-Gateway-HAT-Top_1024x](https://user-images.githubusercontent.com/1878314/57805068-0d8fd900-7754-11e9-8e44-52c4ca5d3c07.png)
![IoT-LoRa-Node-pHAT-Top_1024x (1)](https://user-images.githubusercontent.com/1878314/57806506-2948ae80-7757-11e9-941f-a43fef9c4b51.png)
![IoT-LoRa-Arduino-Shield-Top_1024x (1)](https://user-images.githubusercontent.com/1878314/57806742-ad029b00-7757-11e9-994e-9c1a0afc77f0.png)

**Comment by ChristopherRush** [comment]
![IoT-LoRa-Node-microbit-Top_1024x](https://user-images.githubusercontent.com/1878314/57850762-ac5d1980-77d6-11e9-9197-1018c69ea42f.png)

**Comment by shawaj** [comment]
@ChristopherRush just FYI Louis will be taking new pictures of these soon

**Comment by ChristopherRush** [comment]
@shawaj Perfect, will replace these ones when done.

**Comment by ChristopherRush** [comment]
![IoT-LoRa-Gateway-HAT-Top-No-Module_1024x](https://user-images.githubusercontent.com/1878314/57860384-b7bb3f80-77ec-11e9-8ae0-2a91bca9f24a.png)

**Comment by ChristopherRush** [comment]
![Alliance_member_horiz_CMYK_150dpi](https://user-images.githubusercontent.com/1878314/58036007-efdebd00-7b21-11e9-9ee2-0a251b191bbf.png)

**Comment by monglet** [comment]
Need a new phat photo!

**Comment by ChristopherRush** [comment]
![IoT-LoRa-Node-microbit-Top_1024x-2](https://user-images.githubusercontent.com/1878314/58700166-45735f00-8397-11e9-9612-d2a22d5cedf2.png)

**Comment by ChristopherRush** [comment]
![1_c8ead82b-d3e0-4c66-b121-c168c0e26f7b_1024x](https://user-images.githubusercontent.com/1878314/62480740-f390f000-b7b0-11e9-9f4d-94cecb9655f9.png)
![LoRa-Node-Shield-Top_1024x](https://user-images.githubusercontent.com/1878314/62480748-f7247700-b7b0-11e9-9fab-0b288486d2a4.png)
![1_516121d5-d075-4418-b6bd-36dbc977280e_1024x](https://user-images.githubusercontent.com/1878314/62480754-f986d100-b7b0-11e9-991c-7bbf8dfb3866.png)

**Comment by ChristopherRush** [comment]
[IP67 Case.pdf](https://github.com/PiSupply/IoTLoRaRange/files/3950846/IP67.Case.pdf)

**Comment by shawaj** [comment]
@ChristopherRush just so you are aware this drawing is not completely correct...the holes are the wrong size. I think most of the internals are correct but not the hole bores through the side

**Comment by shawaj** [comment]
@ChristopherRush  <img width="1002" alt="Screenshot 2019-05-31 at 17 49 18 (1)" src="https://user-images.githubusercontent.com/3359418/70631604-4da13680-1c25-11ea-82cf-58011626b5ef.png">

**Comment by ryanteck** [comment]
@shawaj do we have all of the dimensions in Metric as some being imperial and some in metric doesn't make it clear? 

Do we have the metric value for the others?

**Comment by ChristopherRush** [comment]
@shawaj Thanks I did see that other drawing you posted. A customer just wanted the internal dimensions. Do we have a final drawing for the case? We should post it somewhere more visible I guess. Maybe create a repo on the Nebra GitHub.

**Comment by shawaj** [comment]
@ryanteck 5/8-24 is a particular thread type. It does not have a metric equivalent.

@ChristopherRush we do not have a final drawing - but you could just ammend the one you have with the comments on my picture and then it will be correct. Or ask @LouisReed to?

Once we have it, we can post it on Shopify and link to it on the product page and/or make a repo as you say

**Comment by ryanteck** [comment]
@shawaj do we have a link to glands that will fit as I've been asked by customers what glands will fit but haven't been able to find any before and can't with the 5/8-24

**Comment by shawaj** [comment]
@ryanteck 5/8-24 is for the bulkhead connectors, not glands

An M15 or M16 might work - want me to order one of each to you to check?

![image](https://user-images.githubusercontent.com/3359418/70634508-3fa1e480-1c2a-11ea-896d-c035ff4a6749.png)

**Comment by ryanteck** [comment]
If you could maybe, what it is is i've had some customers ask for the bulkhead connectors if there's glands instead for cables to be passed through instead if possible. 

Thanks

**Comment by shawaj** [comment]
@ryanteck m15 doesn't seem to exist. Have ordered an M16 one from RS to you - it will probably be a little tight but since it is plastic going into metal it should work ok I reckon.

**Comment by ryanteck** [comment]
Thanks

**Comment by ChristopherRush** [comment]
![iot-lora-github-banner](https://user-images.githubusercontent.com/1878314/73880726-dcfa4d00-4856-11ea-889d-9e194ee33368.png)

**Comment by ChristopherRush** [comment]
![iot-lora-github-banner](https://user-images.githubusercontent.com/1878314/73938551-66edf880-48df-11ea-9f62-eeb736835a43.png)
