### ISSUE TITLE
Open source System Image

### ISSUE THREAD

**Issue by louai00** [PiSupply/IoTLoRaRange#9]
I am considering using the RPi pHAT as LoRaWAN gateway for research. However, I only found how to using a precompiled image. Are there instructions on how to modify the image and download it on the device?

Thanks

**Comment by ryanteck** [comment]
Hi @louai00 ,

It depends on what you want to modify, we wouldn't really recommend modifying our image and instead for advanced users would then recommend starting from scratch with Raspbian Lite, compiling all of the software and installing it that way.
